title: Keerthana MG
#![logo](https://github.com/keerthanamg/keerthanamg/blob/main/LinkedIn%20%26%20Github%20Banner.png)
logo: DSC_9032 c.jpg
#description: text below image
show downloads: true
theme: jekyll-theme-minimal
