title: Keerthana MG
#![logo](https://github.com/keerthanamg/keerthanamg/blob/main/LinkedIn%20%26%20Github%20Banner.png)
logo: DSC_9032 c.jpg
#description: text below image
show downloads: true
#![logo](https://github.com/keerthanamg/keerthanamg.github.io/blob/main/DALL%C2%B7E%202024-10-22%2020.33.57%20-%20A%20female%20prompt%20engineer%20working%20with%20cutting-edge%20AI%20systems.%20She%20is%20in%20a%20tech-savvy%20workspace%2C%20surrounded%20by%20screens%20showing%20AI-generated%20text%2C%20code.webp)
logo: DALL·E 2024-10-22 20.33.57 - A female prompt engineer working with cutting-edge AI systems. She is in a tech-savvy workspace, surrounded by screens showing AI-generated text, code.webp
theme: jekyll-theme-minimal
